/**
 * This code was generated by "react-native codegen-lib-harmony"
 */

#pragma once

#include "generated/RNOH/generated/turbo_modules/WMDatabaseJSIBridge.h"

namespace rnoh
{

  class JSI_EXPORT RNWMDatabaseJSIBridge : public WMDatabaseJSIBridge
  {
  public:
    RNWMDatabaseJSIBridge(const ArkTSTurboModule::Context ctx, const std::string name);

    void JSIInstall(facebook::jsi::Runtime &rt);
  };

} // namespace rnoh
