#include "RNOH/PackageProvider.h"
#include "generated/RNOHGeneratedPackage.h"
 #include "WatermelondbPackage.h"

using namespace rnoh;

std::vector<std::shared_ptr<Package>> PackageProvider::getPackages(
    Package::Context ctx) {
  return {
      std::make_shared<RNOHGeneratedPackage>(ctx), // generated by codegen v1
         std::make_shared<WatermelondbPackage>(ctx)
  };
}